# Generated by Django 3.1.1 on 2020-09-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('CUS_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CUS_NAME', models.CharField(max_length=70)),
                ('CUS_CITY', models.CharField(max_length=70)),
                ('CUS_MO', models.CharField(max_length=12, unique=True)),
                ('CUS_EMAIL', models.EmailField(max_length=254, unique=True)),
                ('CUS_STATE', models.CharField(max_length=70)),
                ('CUS_Zip', models.CharField(max_length=6)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('CAR_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CAR_MODEL', models.CharField(max_length=20)),
                ('CAR_COLOUR', models.CharField(max_length=20)),
                ('CAR_COMPANY', models.CharField(max_length=20)),
                ('CAR_PRICE_OR', models.IntegerField()),
                ('CAR_PRICE_EX', models.IntegerField()),
                ('CAR_BOOKING_AMT', models.IntegerField()),
                ('CAR_BOOKING_DATE', models.DateField()),
                ('INS_COMPANY_NAME', models.CharField(max_length=20)),
                ('INS_TYPE', models.CharField(max_length=20)),
                ('INS_TOTAL_AMT', models.IntegerField()),
                ('INS_TO_DATE', models.DateField()),
                ('INS_FROM_DATE', models.DateField()),
                ('RTO_REG_CHARGE', models.IntegerField()),
                ('RTO_NUM_PLT_CHARGE', models.IntegerField()),
                ('RTO_NUM_PLT_NO', models.CharField(max_length=20, unique=True)),
                ('RTO_ENG_NO', models.CharField(max_length=20, unique=True)),
                ('RTO_CHESSISE_NO', models.CharField(max_length=20, unique=True)),
                ('RTO_KEY_NO', models.CharField(max_length=20, unique=True)),
                ('RTO_BATTERY_NO', models.CharField(max_length=20, unique=True)),
                ('OTH_TRANS_CHARGE', models.IntegerField()),
                ('OTH_DELIVERY_DATE', models.DateField()),
                ('OTH_EXPENSE_NAME', models.CharField(max_length=20)),
                ('OTH_EXPENSE_PRICE', models.IntegerField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('CUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAR.customer')),
            ],
        ),
    ]
