# Generated by Django 3.1.1 on 2020-09-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0003_auto_20200927_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CUS_FNAME',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='customer',
            name='CUS_SARNAME',
            field=models.CharField(default=None, max_length=70),
        ),
    ]
