# Generated by Django 3.1.1 on 2020-09-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0005_auto_20200928_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CUS_FNAME',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CUS_SARNAME',
        ),
    ]
