# Generated by Django 3.1.1 on 2020-09-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0006_auto_20200928_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CUS_FNAME',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='customer',
            name='CUS_SARNAME',
            field=models.CharField(default='', max_length=70),
        ),
    ]
