# Generated by Django 3.1.1 on 2020-09-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0007_auto_20200928_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CUS_FNAME',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CUS_SARNAME',
            field=models.CharField(max_length=70),
        ),
    ]
