# Generated by Django 3.1.1 on 2020-09-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0008_auto_20200928_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CUS_SARNAME',
            field=models.CharField(max_length=20),
        ),
    ]
